/**
 * GENERATED by tools/build-samples.py — do not edit.
 *
 * One pre-rendered mp3 per English Kokoro voice, in `public/samples/<id>.mp3`,
 * all speaking PREVIEW_LINE. The landing page's Play button picks one at random,
 * so a visitor who presses it twice hears the range rather than the same read.
 *
 * Re-run the generator to add a voice, retire one, or change the line; the audio
 * and this list have to move together, which is why one script writes both.
 */

export const PREVIEW_LINE =
  "coin gremlin cheered 50 bits: Please tell chat what happened to the sandwich";

export const PREVIEW_VOICES = [
  "af_alloy",
  "af_aoede",
  "af_bella",
  "af_heart",
  "af_jessica",
  "af_kore",
  "af_nova",
  "af_river",
  "af_sarah",
  "af_sky",
  "am_adam",
  "am_echo",
  "am_eric",
  "am_fenrir",
  "am_liam",
  "am_michael",
  "am_onyx",
  "am_puck",
  "am_santa",
  "bf_alice",
  "bf_emma",
  "bf_isabella",
  "bf_lily",
  "bm_daniel",
  "bm_fable",
  "bm_george",
  "bm_lewis",
] as const;
