/**
 * GENERATED by tools/build-voice-catalogue.py — do not edit.
 *
 * Every Kokoro voice, grouped by language, with the line its sample speaks. The
 * samples are in `public/voice-samples/<id>.mp3`, re-encoded from the wavs the
 * voice guide plays, so a chip on the setup screen and a card in the guide are the
 * same recording.
 *
 * Baked rather than fetched: the pool picker is where a streamer chooses voices, and
 * it has to work before any engine has answered. `voiceCatalogue.ts` narrows this to
 * what the current build can actually speak.
 *
 * Re-run the generator to add a voice, retire one, or change a sample; the list and
 * the audio have to move together, which is why one script writes both.
 */

export interface CatalogueVoice {
  id: string;
  /** The part after the underscore, capitalised. `af_sky` → "Sky". */
  name: string;
  gender: "Female" | "Male" | null;
  /** What this voice's sample says. */
  line: string;
  /** English gloss, for the lines that are not in English. */
  translation: string | null;
}

export interface VoiceLanguage {
  /** Kokoro's language letter — the first character of every id in the group. */
  code: string;
  country: string;
  flag: string;
  language: string;
  voices: readonly CatalogueVoice[];
}

export const VOICE_CATALOGUE: readonly VoiceLanguage[] = [
  {
    code: "a",
    country: "United States",
    flag: "🇺🇸",
    language: "American English",
    voices: [
      {
        id: "af_alloy",
        name: "Alloy",
        gender: "Female",
        line: "I'll take the large. No, the large large: the one that comes in a bucket with a handle.",
        translation: null,
      },
      {
        id: "af_aoede",
        name: "Aoede",
        gender: "Female",
        line: "Sure, it's a twelve hour drive, but that's basically next door. I just need to grab an iced coffee first.",
        translation: null,
      },
      {
        id: "af_bella",
        name: "Bella",
        gender: "Female",
        line: "This ranch dressing? I brought it from home. You never know.",
        translation: null,
      },
      {
        id: "af_heart",
        name: "Heart",
        gender: "Female",
        line: "Good morning! I am contractually required to ask how you're doing, and I am sincerely thrilled to hear it.",
        translation: null,
      },
      {
        id: "af_jessica",
        name: "Jessica",
        gender: "Female",
        line: "My health insurance covers exactly one of my two kidneys. Provided I can afford the deductible.",
        translation: null,
      },
      {
        id: "af_kore",
        name: "Kore",
        gender: "Female",
        line: "We put ice in everything here. Water, soda, tea. But most importantly: Opinions.",
        translation: null,
      },
      {
        id: "af_nicole",
        name: "Nicole",
        gender: "Female",
        line: "I'd love to chat, but only I have twenty minutes of vacation left for the entire year.",
        translation: null,
      },
      {
        id: "af_nova",
        name: "Nova",
        gender: "Female",
        line: "It's a cheesecake, so why shouldn't I add cheese on top?",
        translation: null,
      },
      {
        id: "af_river",
        name: "River",
        gender: "Female",
        line: "Everything on this menu comes with fries, including the salad. And, I believe, the soup.",
        translation: null,
      },
      {
        id: "af_sarah",
        name: "Sarah",
        gender: "Female",
        line: "Can I please take my coffee to go in my Stanley Cup?",
        translation: null,
      },
      {
        id: "af_sky",
        name: "Sky",
        gender: "Female",
        line: "The recipe called for one stick of butter, so I used four. That's just math.",
        translation: null,
      },
      {
        id: "am_adam",
        name: "Adam",
        gender: "Male",
        line: "I don't need the metric system. I measure distance in football fields and time in seasons of television.",
        translation: null,
      },
      {
        id: "am_echo",
        name: "Echo",
        gender: "Male",
        line: "Sir, this is a Wendy's.",
        translation: null,
      },
      {
        id: "am_eric",
        name: "Eric",
        gender: "Male",
        line: "I bought a truck so big it has its own weather. I use it to carry one bag of mulch, twice a year.",
        translation: null,
      },
      {
        id: "am_fenrir",
        name: "Fenrir",
        gender: "Male",
        line: "The grill is not a cooking appliance. The grill is a personality.",
        translation: null,
      },
      {
        id: "am_liam",
        name: "Liam",
        gender: "Male",
        line: "I tipped the guy who handed me a bottle of water 20%. That's 40 dollars tip.",
        translation: null,
      },
      {
        id: "am_michael",
        name: "Michael",
        gender: "Male",
        line: "Welcome to the store! Ask me about our extended warranty on the warranty.",
        translation: null,
      },
      {
        id: "am_onyx",
        name: "Onyx",
        gender: "Male",
        line: "In this country the eagle screams, the flag waves, and somebody, somewhere, is deep frying a turkey.",
        translation: null,
      },
      {
        id: "am_puck",
        name: "Puck",
        gender: "Male",
        line: "I ordered the small portion and they wheeled it out.",
        translation: null,
      },
      {
        id: "am_santa",
        name: "Santa",
        gender: "Male",
        line: "Ho ho ho! Leave out the cookies, and if you have a soda the size of a fire hydrant, leave that too.",
        translation: null,
      },
    ],
  },
  {
    code: "b",
    country: "United Kingdom",
    flag: "🇬🇧",
    language: "British English",
    voices: [
      {
        id: "bf_alice",
        name: "Alice",
        gender: "Female",
        line: "There's nothing a plate of beans on toast can't fix. Nothing worth fixing, at any rate.",
        translation: null,
      },
      {
        id: "bf_emma",
        name: "Emma",
        gender: "Female",
        line: "I'm terribly sorry. You stepped on my foot, and I apologise for having a foot there in the first place.",
        translation: null,
      },
      {
        id: "bf_isabella",
        name: "Isabella",
        gender: "Female",
        line: "It's fourteen degrees and the sun is out, so the shirts are off and the entire nation is in a beer garden.",
        translation: null,
      },
      {
        id: "bf_lily",
        name: "Lily",
        gender: "Female",
        line: "I have queued for forty minutes and I'd like it on record that I am enjoying myself enormously.",
        translation: null,
      },
      {
        id: "bm_daniel",
        name: "Daniel",
        gender: "Male",
        line: "Oy bruv. Are you having a laugh? I'll smack you with my bottle of water.",
        translation: null,
      },
      {
        id: "bm_fable",
        name: "Fable",
        gender: "Male",
        line: "Aweful weather, isn't it? I say that every day, and every day it is awful.",
        translation: null,
      },
      {
        id: "bm_george",
        name: "George",
        gender: "Male",
        line: "The correct answer is a cup of tea. No matter the question.",
        translation: null,
      },
      {
        id: "bm_lewis",
        name: "Lewis",
        gender: "Male",
        line: "Warm beer, cold house, and a full English breakfast at two in the afternoon.",
        translation: null,
      },
    ],
  },
  {
    code: "e",
    country: "Spain",
    flag: "🇪🇸",
    language: "Spanish",
    voices: [
      {
        id: "ef_dora",
        name: "Dora",
        gender: "Female",
        line: "¿Las ocho de la tarde? Buenísimo, entonces cenamos a las once y media.",
        translation: "Eight in the evening? Great, then we'll have dinner at half eleven.",
      },
      {
        id: "em_alex",
        name: "Alex",
        gender: "Male",
        line: "Lo hacemos mañana. Y si mañana no puede ser, pues pasado mañana también existe.",
        translation: "We'll do it tomorrow. And if tomorrow doesn't work, the day after also exists.",
      },
      {
        id: "em_santa",
        name: "Santa",
        gender: "Male",
        line: "¡Jo, jo, jo! Dejadme jamón y un poquito de turrón, que los villancicos son muy largos.",
        translation: "Ho ho ho! Leave me some ham and a bit of nougat, the carols are long.",
      },
    ],
  },
  {
    code: "f",
    country: "France",
    flag: "🇫🇷",
    language: "French",
    voices: [
      {
        id: "ff_siwis",
        name: "Siwis",
        gender: "Female",
        line: "Il y a une grève, le pain est encore chaud, et le fromage sent très, très fort. Bref, une journée parfaite.",
        translation: "There's a strike on, the bread is still warm, and the cheese smells very strong indeed. In short, a perfect day.",
      },
    ],
  },
  {
    code: "i",
    country: "Italy",
    flag: "🇮🇹",
    language: "Italian",
    voices: [
      {
        id: "if_sara",
        name: "Sara",
        gender: "Female",
        line: "L'ananas sulla pizza? No. E il cappuccino dopo pranzo? Ancora peggio. Adesso chiamo mia nonna.",
        translation: "Pineapple on pizza? No. And a cappuccino after lunch? Worse. I'm calling my grandmother.",
      },
      {
        id: "im_nicola",
        name: "Nicola",
        gender: "Male",
        line: "Se metto le mani in tasca non riesco più a parlare. La pasta si scola al dente, punto.",
        translation: "If I put my hands in my pockets I can't speak any more. Pasta is drained al dente, full stop.",
      },
    ],
  },
  {
    code: "p",
    country: "Brazil",
    flag: "🇧🇷",
    language: "Brazilian Portuguese",
    voices: [
      {
        id: "pf_dora",
        name: "Dora",
        gender: "Female",
        line: "Já estou saindo! Ou seja, ainda estou no banho, mas já estou saindo.",
        translation: "I'm on my way out! That is, I'm still in the shower, but I'm on my way out.",
      },
      {
        id: "pm_alex",
        name: "Alex",
        gender: "Male",
        line: "No churrasco a gente combina meio-dia, chega às três, e come até domingo que vem.",
        translation: "For a barbecue we agree on noon, arrive at three, and eat until next Sunday.",
      },
      {
        id: "pm_santa",
        name: "Santa",
        gender: "Male",
        line: "Ho ho ho! Papai Noel de bermuda e chinelo, porque aqui o Natal tem quarenta graus.",
        translation: "Ho ho ho! Father Christmas in shorts and flip flops, because here Christmas is forty degrees.",
      },
    ],
  },
  {
    code: "h",
    country: "India",
    flag: "🇮🇳",
    language: "Hindi",
    voices: [
      {
        id: "hf_alpha",
        name: "Alpha",
        gender: "Female",
        line: "चाय के बिना कोई बात शुरू नहीं होती। पहले चाय, फिर बाकी दुनिया।",
        translation: "Nothing starts without chai. First the tea, then the rest of the world.",
      },
      {
        id: "hf_beta",
        name: "Beta",
        gender: "Female",
        line: "बस पाँच मिनट में पहुँच रहे हैं। मतलब अभी निकले भी नहीं हैं, लेकिन पहुँच रहे हैं।",
        translation: "We're arriving in just five minutes. Meaning we haven't left, but we're arriving.",
      },
      {
        id: "hm_omega",
        name: "Omega",
        gender: "Male",
        line: "खाने में मिर्च थोड़ी कम है। तुम्हारे लिए ठीक है, हमारे लिए तो मीठा है।",
        translation: "This food is a little short on chilli. Fine for you, sweet for us.",
      },
      {
        id: "hm_psi",
        name: "Psi",
        gender: "Male",
        line: "क्रिकेट मैच चल रहा है, तो ऑफिस, ट्रैफिक और शादी, सब इंतज़ार कर सकते हैं।",
        translation: "The cricket match is on, so the office, the traffic and the wedding can all wait.",
      },
    ],
  },
  {
    code: "j",
    country: "Japan",
    flag: "🇯🇵",
    language: "Japanese",
    voices: [
      {
        id: "jf_alpha",
        name: "Alpha",
        gender: "Female",
        line: "すみません、すみません。なにも わるくないですけど、とりあえず、すみません。",
        translation: "Sorry, sorry. Nothing is wrong, but, for now, sorry.",
      },
      {
        id: "jf_gongitsune",
        name: "Gongitsune",
        gender: "Female",
        line: "でんしゃが にじゅうびょう おくれました。しゃしょうさんが じゅっかい あやまりました。",
        translation: "The train was twenty seconds late. The conductor apologised ten times.",
      },
      {
        id: "jf_nezumi",
        name: "Nezumi",
        gender: "Female",
        line: "コンビニのおにぎりは、あさごはんで、ひるごはんで、ばんごはんです。",
        translation: "A convenience store rice ball is breakfast, lunch and dinner.",
      },
      {
        id: "jf_tebukuro",
        name: "Tebukuro",
        gender: "Female",
        line: "じどうはんばいきが おおすぎます。じどうはんばいきを うる じどうはんばいきも、たぶん あります。",
        translation: "There are far too many vending machines. There is probably even a vending machine that sells vending machines.",
      },
      {
        id: "jm_kumo",
        name: "Kumo",
        gender: "Male",
        line: "きょうも ざんぎょうです。しゅうでんで かえって、コンビニで あたらしい あじの キットカットを かいます。",
        translation: "Overtime again today. I'll take the last train home and buy a new KitKat flavour on the way.",
      },
    ],
  },
  {
    code: "z",
    country: "China",
    flag: "🇨🇳",
    language: "Mandarin Chinese",
    voices: [
      {
        id: "zf_xiaobei",
        name: "Xiaobei",
        gender: "Female",
        line: "吃了吗？没吃的话，先喝点热水，然后我们去吃火锅。",
        translation: "Have you eaten? If not, drink some hot water first, then we'll go for hotpot.",
      },
      {
        id: "zf_xiaoni",
        name: "Xiaoni",
        gender: "Female",
        line: "多喝热水。感冒了喝热水，心情不好也喝热水。",
        translation: "Drink more hot water. Got a cold? Hot water. Feeling sad? Also hot water.",
      },
      {
        id: "zf_xiaoxiao",
        name: "Xiaoxiao",
        gender: "Female",
        line: "我出门只带手机，钱包在家躺着，已经三年没用过了。",
        translation: "I leave the house with only my phone. My wallet has been lying at home for three years.",
      },
      {
        id: "zf_xiaoyi",
        name: "Xiaoyi",
        gender: "Female",
        line: "这个拼单能便宜三块钱，我已经拉了五个群了。",
        translation: "I can save three yuan on this with a group order. I've already started five chat groups.",
      },
      {
        id: "zm_yunjian",
        name: "Yunjian",
        gender: "Male",
        line: "麻将不是游戏，是我们家的传统体育项目。",
        translation: "Mahjong is not a game. It is our family's traditional sport.",
      },
      {
        id: "zm_yunxi",
        name: "Yunxi",
        gender: "Male",
        line: "我妈问我什么时候结婚，我说等我吃完这顿饭再说。",
        translation: "My mother asked when I'm getting married. I said, right after I finish this meal.",
      },
      {
        id: "zm_yunxia",
        name: "Yunxia",
        gender: "Male",
        line: "保温杯里泡枸杞，养生从今天开始，或者明天。",
        translation: "Goji berries steeping in the thermos. Healthy living starts today, or tomorrow.",
      },
      {
        id: "zm_yunyang",
        name: "Yunyang",
        gender: "Male",
        line: "外卖二十分钟就送到了，我却花了四十分钟才决定吃什么。",
        translation: "The delivery arrived in twenty minutes. It took me forty to decide what to order.",
      },
    ],
  },
];
