/**
 * The voices the pool picker offers, and where to hear one.
 *
 * The list itself is **baked in**, generated by `tools/build-voice-catalogue.py` into
 * `voiceCatalogueData.ts` from the voice guide's own catalogue — Kokoro's 54 voices with
 * their country, gender and the line their sample speaks. It used to be whatever the engine
 * had published (`bot.voices`), which meant the one screen where a streamer chooses voices
 * needed a reachable engine to render at all, and rendered a *different* list depending on
 * which build they had opened. A fixed catalogue is what it always was in practice.
 *
 * What is still per-build is which of them this bundle can speak, and that is the only thing
 * this module decides: the browser engine synthesises through kokoro-js, whose `VOICES` map
 * carries the English ids alone (see CLAUDE.md, "The browser engine"), so a browser build
 * shows 28 and a server build shows all 54. The narrowing is by Kokoro's language letter
 * rather than by an id list, so a new English voice needs nothing here.
 *
 * A voice this build cannot speak is not thereby dropped from a streamer's *pool*: the two
 * builds share one settings blob, and `VoicePool` keeps the ids it cannot show. See
 * `randomPool` in `userVoices.ts`.
 */

import { withBasePath } from "@/lib/basePath";
import { IS_BROWSER_ENGINE } from "@/lib/ttsEngine";
import { VOICE_CATALOGUE, type CatalogueVoice, type VoiceLanguage } from "./voiceCatalogueData";

export type { CatalogueVoice, VoiceLanguage };

/** Kokoro's language letters for English — `a` American, `b` British. */
const ENGLISH_CODES = new Set(["a", "b"]);

/** Every voice Kokoro has, grouped. What `/avatar` can speak on either build. */
export const ALL_VOICE_GROUPS: readonly VoiceLanguage[] = VOICE_CATALOGUE;

/** The groups this build can synthesise: all of them, or the English ones in the browser. */
export const VOICE_GROUPS: readonly VoiceLanguage[] = IS_BROWSER_ENGINE
  ? ALL_VOICE_GROUPS.filter((g) => ENGLISH_CODES.has(g.code))
  : ALL_VOICE_GROUPS;

/** The same ids, flat and lower-case, as the pool is stored. */
export const VOICE_IDS: readonly string[] = VOICE_GROUPS.flatMap((g) =>
  g.voices.map((v) => v.id),
);

/**
 * The pre-rendered sample for one voice, in `public/voice-samples/`.
 *
 * A static mp3 rather than a synthesis, for the same reason the landing page's preview is
 * one: sampling 54 voices from a setup screen would be 54 requests through the relay on a
 * server build, and 86 MB of weights before the first one on a browser build. `withBasePath`
 * because a bare fetch does not get Next's `basePath` — see CLAUDE.md, "Deployment".
 */
export function voiceSampleUrl(id: string): string {
  return withBasePath(`/voice-samples/${id.toLowerCase()}.mp3`);
}

/** The sample's line, with its gloss when the line is not in English. */
export function sampleCaption(voice: CatalogueVoice): string {
  return voice.translation ? `${voice.line}\n${voice.translation}` : voice.line;
}

/**
 * Where a streamer (or a chatter) can hear the voices, from `NEXT_PUBLIC_VOICE_GUIDE_URL`.
 *
 * Build-time and public, like every other `NEXT_PUBLIC_*` here: changing it needs
 * `docker compose up -d --build`, not a restart.
 *
 * **No default, and unset is not an error** — the two differ from `TTS_BASE_URL` on purpose.
 * There is no guess to make: a guide is one deployment's static page (the reference one
 * serves `../../voice-guide` at `/tts-guide`), so a fallback would be a link to somebody
 * else's hostname. Unset simply renders no link, and the picker — which now plays the guide's
 * own samples itself — is fully usable without one.
 */
export const VOICE_GUIDE_URL = (process.env.NEXT_PUBLIC_VOICE_GUIDE_URL ?? "").trim();
