#!/usr/bin/env python3
"""
Render the landing page's "Play preview" samples from a real Kokoro instance.

The homepage claims a viewer's cheer gets "read aloud, the way your viewers will". The
browser's own `speechSynthesis` cannot honour that: it is whatever voice the visitor's OS
ships, which is exactly the thing this app replaces. So the samples are pre-rendered here,
once, from `../server` — the same engine and the same phrasing the bot uses live — and the
page plays a random one.

Pre-rendered rather than synthesised in the page on purpose. The browser-engine build would
have to pull 86 MB of weights before an unsigned-in visitor heard anything, and the
server-engine build would be pointing a public page at the Kokoro relay. A static mp3 costs
one ~45 KB fetch, on click, and behaves identically on both builds.

Usage:
    python3 tools/build-samples.py [http://127.0.0.1:8020]

Writes:
    public/samples/<voice>.mp3     one per English voice
    src/lib/previewSamples.ts      the generated voice list the page imports

Needs `ffmpeg` on PATH (mp3, not the server's wav: 27 wavs are ~6 MB, the mp3s are ~1 MB).
"""

import json
import os
import subprocess
import sys
import tempfile
import urllib.error
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
WEB = os.path.dirname(HERE)
OUT_AUDIO = os.path.join(WEB, "public", "samples")
OUT_LIST = os.path.join(WEB, "src", "lib", "previewSamples.ts")

DEFAULT_BASE = "http://127.0.0.1:8020"

# The line the bot itself would speak for the cheer drawn in the homepage's chat demo:
# `${displayName} cheered ${bits} bits: ${body}`, verbatim from `handleChat` in lib/bot.ts.
# The one departure is the underscore in `coin_gremlin` — espeak reads punctuation inside a
# word rather than gliding over it, and "coin underscore gremlin" is not what a viewer hears.
LINE = "coin gremlin cheered 50 bits: Please tell chat what happened to the sandwich"

# Kokoro prefixes every voice id with its language: `a` is American English, `b` is British.
# Those are the only two the preview uses — the page is in English, and the browser-engine
# build cannot speak the other 26 anyway (kokoro-js maps only these).
ENGLISH_PREFIXES = ("af_", "am_", "bf_", "bm_")

# Excluded by request.
EXCLUDE = {"af_nicole"}

SPEED = 1.0
MP3_BITRATE = "64k"


def get_json(url: str):
    with urllib.request.urlopen(url, timeout=20) as r:
        return json.loads(r.read().decode("utf-8"))


def synthesise(base: str, voice: str, dest: str) -> None:
    """POST one line and write the wav. `format: wav` here, unlike the app's `pcm` — ffmpeg
    wants a container, and nothing is streaming."""
    body = json.dumps({"text": LINE, "voice": voice, "speed": SPEED, "format": "wav"}).encode()
    req = urllib.request.Request(
        f"{base}/tts",
        data=body,
        headers={"Content-Type": "application/json", "User-Agent": "MoneybotTTS/build-samples"},
    )
    # Generous: the service is CPU-only and synthesises a sentence at a time.
    with urllib.request.urlopen(req, timeout=180) as r:
        audio = r.read()
    if len(audio) < 1024:
        raise RuntimeError(f"{voice}: server returned {len(audio)} bytes, which is not audio")
    with open(dest, "wb") as f:
        f.write(audio)


def encode(src_wav: str, dest_mp3: str) -> None:
    subprocess.run(
        ["ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
         "-i", src_wav, "-ac", "1", "-codec:a", "libmp3lame", "-b:a", MP3_BITRATE, dest_mp3],
        check=True,
    )


def write_list(voices) -> None:
    """`voices` is a list of ids. Unannotated: the host's python is old enough that a
    builtin generic in a signature is a TypeError at import."""
    body = "\n".join(f'  "{v}",' for v in voices)
    with open(OUT_LIST, "w", encoding="utf-8") as f:
        f.write(
            "/**\n"
            " * GENERATED by tools/build-samples.py — do not edit.\n"
            " *\n"
            " * One pre-rendered mp3 per English Kokoro voice, in `public/samples/<id>.mp3`,\n"
            " * all speaking PREVIEW_LINE. The landing page's Play button picks one at random,\n"
            " * so a visitor who presses it twice hears the range rather than the same read.\n"
            " *\n"
            " * Re-run the generator to add a voice, retire one, or change the line; the audio\n"
            " * and this list have to move together, which is why one script writes both.\n"
            " */\n\n"
            f'export const PREVIEW_LINE =\n  "{LINE}";\n\n'
            "export const PREVIEW_VOICES = [\n"
            f"{body}\n"
            "] as const;\n"
        )


def main() -> int:
    base = (sys.argv[1] if len(sys.argv) > 1 else os.environ.get("TTS_BASE_URL", DEFAULT_BASE)).rstrip("/")

    try:
        catalogue = get_json(f"{base}/voices")
    except (urllib.error.URLError, OSError) as e:
        print(f"Cannot reach {base}/voices: {e}", file=sys.stderr)
        print("Start the TTS stack first: (cd ../server && docker compose up -d)", file=sys.stderr)
        return 1

    voices = sorted(
        v for v in catalogue.get("voices", [])
        if v.startswith(ENGLISH_PREFIXES) and v not in EXCLUDE
    )
    if not voices:
        print(f"No English voices in the catalogue of {catalogue.get('count')}", file=sys.stderr)
        return 1

    os.makedirs(OUT_AUDIO, exist_ok=True)
    print(f"{len(voices)} voices from {base}\n  line: {LINE}\n")

    with tempfile.TemporaryDirectory() as tmp:
        for i, voice in enumerate(voices, 1):
            wav = os.path.join(tmp, f"{voice}.wav")
            mp3 = os.path.join(OUT_AUDIO, f"{voice}.mp3")
            print(f"  [{i:2}/{len(voices)}] {voice} … ", end="", flush=True)
            # Sequential, deliberately: espeak's phonemizer backend is a process-wide cached
            # object and not thread-safe, so parallel requests kill each other and the loser
            # gets a header with no audio behind it.
            synthesise(base, voice, wav)
            encode(wav, mp3)
            print(f"{os.path.getsize(mp3) // 1024} KB")

    write_list(voices)
    total = sum(os.path.getsize(os.path.join(OUT_AUDIO, f"{v}.mp3")) for v in voices)
    print(f"\nWrote {len(voices)} mp3s ({total // 1024} KB) to public/samples/")
    print(f"Wrote {os.path.relpath(OUT_LIST, WEB)}")

    stale = sorted(
        f for f in os.listdir(OUT_AUDIO)
        if f.endswith(".mp3") and f[:-4] not in voices
    )
    if stale:
        print(f"\nStale, no longer in the list — delete by hand: {', '.join(stale)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
