#!/usr/bin/env python3
"""
Bake the voice list the setup screen's pool picker shows, and the sample each chip plays.

The picker used to render whatever `/voices` (or kokoro-js) handed over, which made the one
screen where a streamer chooses voices depend on a reachable engine: no list, no choosing.
It is a fixed catalogue in practice — Kokoro's 54 voices, of which the browser engine speaks
the 28 English ones — so it is baked in here instead and the screen works before anything
has connected.

The samples are the *same wavs the voice guide plays* (`../voice-guide/public/samples`), one
line per voice, so a streamer hears exactly what the guide would play them and the two never
disagree about how a voice sounds. They are re-encoded rather than copied: 54 wavs are 13 MB,
the mp3s are about 2 MB, and this directory's audio is already mp3 for that reason (see
tools/build-samples.py).

`../voice-guide/public/voices.js` is the source for the list, not `../server`, and
deliberately: it is generated from `../server/scripts/sample_voices.py` by the guide's own
`tools/build-voices.py`, and it is the file that comes with the wavs — reading it here means
the caption, the country grouping and the audio cannot drift apart. Re-run the guide's
generator first if a voice is new.

Usage:
    python3 tools/build-voice-catalogue.py

Writes:
    public/voice-samples/<voice>.mp3     one per voice in the guide's catalogue
    src/lib/voiceCatalogueData.ts        the generated list the picker renders

Needs `ffmpeg` on PATH.
"""

import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
WEB = os.path.dirname(HERE)
GUIDE = os.path.join(os.path.dirname(WEB), "voice-guide", "public")

SRC_LIST = os.path.join(GUIDE, "voices.js")
SRC_AUDIO = os.path.join(GUIDE, "samples")
OUT_AUDIO = os.path.join(WEB, "public", "voice-samples")
OUT_LIST = os.path.join(WEB, "src", "lib", "voiceCatalogueData.ts")

MP3_BITRATE = "64k"


def read_catalogue():
    """`voices.js` is one `window.VOICE_CATALOGUE = [...]` assignment of pure JSON, so the
    array slices straight out of it — no JS engine and no dependency involved."""
    raw = open(SRC_LIST, encoding="utf-8").read()
    start, end = raw.index("["), raw.rindex("]")
    return json.loads(raw[start : end + 1])


def encode(src_wav: str, dest_mp3: str) -> None:
    subprocess.run(
        ["ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
         "-i", src_wav, "-ac", "1", "-codec:a", "libmp3lame", "-b:a", MP3_BITRATE, dest_mp3],
        check=True,
    )


def ts(value) -> str:
    """JSON is valid TS for everything here, and json.dumps escapes the quotes and the
    non-ASCII lines (Japanese, Mandarin) that a hand-rolled writer would get wrong."""
    return json.dumps(value, ensure_ascii=False)


def write_list(groups) -> None:
    out = [
        "/**",
        " * GENERATED by tools/build-voice-catalogue.py — do not edit.",
        " *",
        " * Every Kokoro voice, grouped by language, with the line its sample speaks. The",
        " * samples are in `public/voice-samples/<id>.mp3`, re-encoded from the wavs the",
        " * voice guide plays, so a chip on the setup screen and a card in the guide are the",
        " * same recording.",
        " *",
        " * Baked rather than fetched: the pool picker is where a streamer chooses voices, and",
        " * it has to work before any engine has answered. `voiceCatalogue.ts` narrows this to",
        " * what the current build can actually speak.",
        " *",
        " * Re-run the generator to add a voice, retire one, or change a sample; the list and",
        " * the audio have to move together, which is why one script writes both.",
        " */",
        "",
        "export interface CatalogueVoice {",
        "  id: string;",
        "  /** The part after the underscore, capitalised. `af_sky` → \"Sky\". */",
        "  name: string;",
        '  gender: "Female" | "Male" | null;',
        "  /** What this voice's sample says. */",
        "  line: string;",
        "  /** English gloss, for the lines that are not in English. */",
        "  translation: string | null;",
        "}",
        "",
        "export interface VoiceLanguage {",
        "  /** Kokoro's language letter — the first character of every id in the group. */",
        "  code: string;",
        "  country: string;",
        "  flag: string;",
        "  language: string;",
        "  voices: readonly CatalogueVoice[];",
        "}",
        "",
        "export const VOICE_CATALOGUE: readonly VoiceLanguage[] = [",
    ]

    for group in groups:
        out.append("  {")
        for key in ("code", "country", "flag", "language"):
            out.append(f"    {key}: {ts(group[key])},")
        out.append("    voices: [")
        for voice in group["voices"]:
            out.append("      {")
            out.append(f"        id: {ts(voice['id'])},")
            out.append(f"        name: {ts(voice['name'])},")
            out.append(f"        gender: {ts(voice['gender']) if voice.get('gender') else 'null'},")
            out.append(f"        line: {ts(voice['line'])},")
            translation = voice.get("translation")
            out.append(f"        translation: {ts(translation) if translation else 'null'},")
            out.append("      },")
        out.append("    ],")
        out.append("  },")

    out += ["];", ""]
    with open(OUT_LIST, "w", encoding="utf-8") as f:
        f.write("\n".join(out))


def main() -> int:
    if not os.path.isfile(SRC_LIST):
        print(f"No catalogue at {SRC_LIST} — run ../voice-guide/tools/build-voices.py first",
              file=sys.stderr)
        return 1

    groups = read_catalogue()
    ids = [v["id"] for g in groups for v in g["voices"]]
    os.makedirs(OUT_AUDIO, exist_ok=True)
    print(f"{len(ids)} voices in {len(groups)} languages from {os.path.relpath(SRC_LIST, WEB)}\n")

    missing, total = [], 0
    for i, voice_id in enumerate(ids, 1):
        wav = os.path.join(SRC_AUDIO, f"{voice_id}.wav")
        mp3 = os.path.join(OUT_AUDIO, f"{voice_id}.mp3")
        if not os.path.isfile(wav):
            # Not fatal: a voice with no wav still belongs in the list, and the picker hides
            # the play button for it rather than offering a 404.
            missing.append(voice_id)
            print(f"  [{i:2}/{len(ids)}] {voice_id} … no wav in the guide, skipped")
            continue
        print(f"  [{i:2}/{len(ids)}] {voice_id} … ", end="", flush=True)
        encode(wav, mp3)
        size = os.path.getsize(mp3)
        total += size
        print(f"{size // 1024} KB")

    write_list(groups)
    print(f"\nWrote {len(ids) - len(missing)} mp3s ({total // 1024} KB) to public/voice-samples/")
    print(f"Wrote {os.path.relpath(OUT_LIST, WEB)}")

    if missing:
        print(f"\nNo sample for: {', '.join(missing)}")
    stale = sorted(
        f for f in os.listdir(OUT_AUDIO) if f.endswith(".mp3") and f[:-4] not in ids
    )
    if stale:
        print(f"\nStale, no longer in the catalogue — delete by hand: {', '.join(stale)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
